version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq

  car-service:
    build: ./car-service
    ports:
      - "8082:8082"
    depends_on:
      - rabbitmq
